services:
  dev:
    image: node:20-alpine
    container_name: marketcap-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketcap-prod
    ports:
      - 8080:80
    environment:
      - NODE_ENV=production
    restart: unless-stopped
